import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import ButtonAppBar from "./ButtonAppBar";
import CssBaseline from '@mui/material/CssBaseline';
import DarkTheme from "./DarkTheme";

export const metadata: Metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <DarkTheme>
            <CssBaseline />
            <ButtonAppBar />
            {children}
          </DarkTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
